name: Run Java Program

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Compile Java code
      run: javac MyProgram.java

    - name: Run Java program
      run: java MyProgram
